# Adversarial / attack related defaults
advtrain: False
attack_criterion: mixup
attack_norm: linf
advprop: False
attack_eps: 0.0
attack_step: 1.0
attack_it: 3
bce_loss: False


# GradNorm related defaults
gradnorm: False
lambda_ce: 0.8
lambda_gn: 1.2