# Adversarial / attack related defaults
advtrain: True
attack_criterion: mixup
attack_norm: linf
advprop: False
attack_eps: 2.0
attack_step: 3.0
attack_it: 3
bce_loss: False


# GradNorm related defaults
gradnorm: False
lambda_ce: 0.8
lambda_gn: 1.2